//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRP.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Garage
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Garage()
        {
            this.Vehicles = new HashSet<Vehicle>();
        }
    
        public int ID { get; set; }
        public int OwnerID { get; set; }
        public string Name { get; set; }
        public int LocationID { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public string Phone1 { get; set; }
        public string Phone2 { get; set; }
        public Nullable<decimal> Star { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> OpenTimeMon { get; set; }
        public Nullable<System.DateTime> CloseTimeMon { get; set; }
        public Nullable<System.DateTime> OpenTimeTue { get; set; }
        public Nullable<System.DateTime> CloseTimeTue { get; set; }
        public Nullable<System.DateTime> OpenTImeWed { get; set; }
        public Nullable<System.DateTime> CloseTImeWed { get; set; }
        public Nullable<System.DateTime> OpenTimeThur { get; set; }
        public Nullable<System.DateTime> CloseTimeThur { get; set; }
        public Nullable<System.DateTime> OpenTimeFri { get; set; }
        public Nullable<System.DateTime> CloseTimeFri { get; set; }
        public Nullable<System.DateTime> OpenTimeSat { get; set; }
        public Nullable<System.DateTime> CloseTimeSat { get; set; }
        public Nullable<System.DateTime> OpenTimeSun { get; set; }
        public Nullable<System.DateTime> CloseTimeSun { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vehicle> Vehicles { get; set; }
        public virtual User User { get; set; }
    }
}
