//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRP
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookingReceipt
    {
        public int ID { get; set; }
        public int CustomerID { get; set; }
        public int CarScheduleID { get; set; }
        public double TotalPrice { get; set; }
        public double BookingFee { get; set; }
        public Nullable<decimal> Star { get; set; }
        public string Comment { get; set; }
    
        public virtual CarSchedulePlan CarSchedulePlan { get; set; }
        public virtual User User { get; set; }
    }
}
