//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Car()
        {
            this.CarEquipments = new HashSet<CarEquipment>();
            this.CarImages = new HashSet<CarImage>();
            this.CarSchedulePlans = new HashSet<CarSchedulePlan>();
        }
    
        public int ID { get; set; }
        public string LicenseNumber { get; set; }
        public int CarVersionID { get; set; }
        public int TransmissionType { get; set; }
        public Nullable<int> FuelType { get; set; }
        public Nullable<int> Power { get; set; }
        public Nullable<int> Engine { get; set; }
        public Nullable<int> NumOfDoor { get; set; }
        public int NumOfSeat { get; set; }
        public string Color { get; set; }
        public Nullable<int> TravelDistance { get; set; }
        public int StoreID { get; set; }
        public string Description { get; set; }
        public decimal Star { get; set; }
        public Nullable<int> CarGroupID { get; set; }
    
        public virtual CarGroup CarGroup { get; set; }
        public virtual CarVersion CarVersion { get; set; }
        public virtual Garage Garage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CarEquipment> CarEquipments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CarImage> CarImages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CarSchedulePlan> CarSchedulePlans { get; set; }
    }
}
