//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRP
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarEquipment
    {
        public int ID { get; set; }
        public int CarID { get; set; }
        public int EquipmentID { get; set; }
    
        public virtual Car Car { get; set; }
        public virtual Equipment Equipment { get; set; }
    }
}
