//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRP
{
    using System;
    using System.Collections.Generic;
    
    public partial class PriceGroup
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public int CarGroupID { get; set; }
        public double Deposit { get; set; }
        public int Type { get; set; }
        public double PricePerPeriod { get; set; }
        public Nullable<int> Period { get; set; }
    
        public virtual CarGroup CarGroup { get; set; }
    }
}
